[package]
name = "coldctl-connector-mysql"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
coldctl-core.workspace = true
coldctl-connector-protocol.workspace = true
coldctl-connector-runtime = { path = "../coldctl-connector-runtime" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "io-std"] }
mysql_async = { version = "0.37.1", default-features = false, features = ["minimal-rust", "native-tls-tls"] }
sha2 = "0.11"
[dev-dependencies]
tempfile = "3"
native-tls = "0.2"
