[workspace]
default-members = ["crates/coldctl"]
members = [
    "crates/coldctl",
    "crates/coldctl-core",
    "crates/coldctl-cloud",
    "crates/coldctl-connector-protocol",
    "crates/coldctl-connector-runtime",
    "crates/coldctl-connector-postgres",
    "crates/coldctl-connector-mysql",
    "crates/coldctl-connector-mongodb",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/coldctl/coldctl"
homepage = "https://www.coldctl.com"

[workspace.dependencies]
coldctl-core = { version = "0.1.1", path = "crates/coldctl-core" }
coldctl-cloud = { version = "0.1.1", path = "crates/coldctl-cloud" }
clap = { version = "4", features = ["derive"] }

coldctl-connector-protocol = { version = "0.1.1", path = "crates/coldctl-connector-protocol" }
