[package]
name = "coldctl-core"
description = "Core domain and archive orchestration for coldctl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
coldctl-connector-protocol.workspace = true
directories = "6"
rusqlite = { version = "0.38", features = ["bundled", "backup"] }
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
percent-encoding = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
coldctl-connector-runtime = { path = "../coldctl-connector-runtime" }

tempfile = "3"
arrow-array = "56"
arrow-schema = "60"
parquet = { version = "56", default-features = false, features = ["arrow", "snap"] }
sha2 = "0.10"
fs2 = "0.4"

tough = "0.24"
reqwest = { version = "0.12", features = ["stream"] }
async-trait = "0.1"
futures-util = "0.3"
semver = "1"
bson = "2.15"

[dev-dependencies]
ring = "0.17"
olpc-cjson = "0.1"
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
native-tls = "0.2"
postgres-native-tls = "0.5"
